server:
  port: 707

http:
  pool:
    # 连接超时
    connectTimeout: 5000
    #获取连接池中连接超时
    connectionRequestTimeout: 1000
    #每个路由最大连接数量
    defaultMaxPerRoute: 5
    # /连接池中最大连接数
    maxTotal: 5
    # 服务器返回数据(response)的时间
    socketTimeout: 5000

